//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_Coopenae.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColocacionProducto
    {
        public int IdColocacionProducto { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Cedula { get; set; }
        public string Nombre { get; set; }
        public string CentroTrabajo { get; set; }
        public int Producto { get; set; }
        public int Ejecutivo { get; set; }
    }
}
