//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_Coopenae.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColocacionCredito
    {
        public int IdColocacionCredito { get; set; }
        public System.DateTime FechaFormalizacion { get; set; }
        public int Cedula { get; set; }
        public string CentroTrabajo { get; set; }
        public string Sector { get; set; }
        public System.DateTime FechaAfiliacion { get; set; }
        public int NumeroOperacion { get; set; }
        public string Sucursal { get; set; }
        public double MontoDesembolsado { get; set; }
        public string PlazoMeses { get; set; }
        public int TipoCredito { get; set; }
        public int Ejecutivo { get; set; }
    }
}
