//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_Coopenae.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejecutivos
    {
        public int Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Sexo { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string CodigoVendedor { get; set; }
        public string Residencia { get; set; }
        public int Sucursal { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public System.DateTime FechaContratacion { get; set; }
        public int Estado { get; set; }
        public int MetaAparte { get; set; }
        public int Salario { get; set; }
    
        public virtual Sucursal Sucursal1 { get; set; }
    }
}
