//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_Coopenae.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public decimal ComisionGenera { get; set; }
        public int EsDolar { get; set; }
        public int Estado { get; set; }
    }
}
