//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPC_Coopenae.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCredito
    {
        public int IdCredito { get; set; }
        public string NombreDeCredito { get; set; }
        public double ComisionDirefente { get; set; }
        public int Estado { get; set; }
    }
}
